In [4]:
import pandas as pd
import numpy as np
import os
os.listdir('./')

['03_AI_Math',
 '01_AI_Bigdata_Programming',
 '.ipynb_checkpoints',
 '02_DataModeling_SQL']

In [6]:
df = pd.read_csv('01_AI_Bigdata_Programming/data/01_seoul_accident_raw.csv', encoding='euc-kr')
df.head()

,사고번호,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,법규위반,...,기상상태,도로형태,가해운전자차종,가해운전자성별,가해운전자연령,가해운전자상해정도,피해운전자차종,피해운전자성별,피해운전자연령,피해운전자상해정도
0,A2019010100100001,2019년 1월 1일 00시,서울특별시 강서구 방화동,경상사고,0,0,1,0,차대사람 - 횡단중,보행자보호의무위반,...,맑음,교차로 - 교차로횡단보도내,승용,남,26세,상해없음,보행자,남,40세,경상
1,A2019010100100002,2019년 1월 1일 00시,서울특별시 구로구 고척동,경상사고,0,0,1,0,차대차 - 추돌,안전운전불이행,...,맑음,단일로 - 기타,이륜,남,23세,상해없음,승용,남,71세,경상
2,A2019010100100003,2019년 1월 1일 00시,서울특별시 서초구 서초동,경상사고,0,0,1,0,차대차 - 기타,안전운전불이행,...,맑음,기타 - 기타,승용,남,33세,상해없음,화물,남,51세,경상
3,A2019010100100019,2019년 1월 1일 01시,서울특별시 중구 회현동2가,경상사고,0,0,1,0,차대차 - 측면충돌,안전운전불이행,...,맑음,단일로 - 터널,승용,남,58세,상해없음,승용,남,62세,경상
4,A2019010100100020,2019년 1월 1일 01시,서울특별시 성동구 행당동,경상사고,0,0,1,0,차대사람 - 횡단중,안전운전불이행,...,맑음,교차로 - 교차로부근,승용,남,30세,상해없음,보행자,남,32세,경상

In [8]:
df.tail()

,사고번호,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,법규위반,...,기상상태,도로형태,가해운전자차종,가해운전자성별,가해운전자연령,가해운전자상해정도,피해운전자차종,피해운전자성별,피해운전자연령,피해운전자상해정도
74480,A2020123100100571,2020년 12월 31일 22시,서울특별시 동대문구 제기동,경상사고,0,0,1,0,차대차 - 기타,안전운전불이행,...,맑음,단일로 - 기타,화물,남,35세,상해없음,자전거,남,41세,경상
74481,A2020123100100572,2020년 12월 31일 22시,서울특별시 강동구 강일동,경상사고,0,0,1,0,차대차 - 정면충돌,중앙선침범,...,흐림,교차로 - 교차로부근,승용,남,61세,상해없음,승용,남,21세,경상
74482,A2020123100100591,2020년 12월 31일 23시,서울특별시 강남구 삼성동,경상사고,0,0,2,0,차대차 - 추돌,교차로운행방법위반,...,맑음,교차로 - 교차로안,승용,남,55세,NaN,승용,남,29세,경상
74483,A2020123100100592,2020년 12월 31일 23시,서울특별시 송파구 신천동,중상사고,0,1,0,0,차대차 - 측면충돌,불법유턴,...,맑음,단일로 - 기타,승용,남,62세,상해없음,이륜,남,22세,중상
74484,A2020123100100593,2020년 12월 31일 23시,서울특별시 양천구 신월동,경상사고,0,0,4,0,차대차 - 측면충돌,안전운전불이행,...,맑음,단일로 - 기타,승용,남,61세,상해없음,승용,남,22세,경상

In [7]:
df.info() #결측치 개수 확인 가능, int는 결측치가 없고, float은 결측치 있음.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74485 entries, 0 to 74484
Data columns (total 21 columns):
사고번호         74485 non-null object
사고일시         74485 non-null object
시군구          74485 non-null object
사고내용         74485 non-null object
사망자수         74485 non-null int64
중상자수         74485 non-null int64
경상자수         74485 non-null int64
부상신고자수       74485 non-null int64
사고유형         74485 non-null object
법규위반         74485 non-null object
노면상태         74485 non-null object
기상상태         73575 non-null object
도로형태         74485 non-null object
가해운전자차종      72734 non-null object
가해운전자성별      72738 non-null object
가해운전자연령      72727 non-null object
가해운전자상해정도    70172 non-null object
피해운전자차종      72225 non-null object
피해운전자성별      72225 non-null object
피해운전자연령      72049 non-null object
피해운전자상해정도    72225 non-null object
dtypes: int64(4), object(17)
memory usage: 11.9+ MB

In [13]:
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74485 entries, 0 to 74484
Data columns (total 21 columns):
사고번호         74485 non-null object
사고일시         74485 non-null object
시군구          74485 non-null object
사고내용         74485 non-null object
사망자수         74485 non-null int64
중상자수         74485 non-null int64
경상자수         74485 non-null int64
부상신고자수       74485 non-null int64
사고유형         74485 non-null object
법규위반         74485 non-null object
노면상태         74485 non-null object
기상상태         73575 non-null object
도로형태         74485 non-null object
가해운전자차종      72734 non-null object
가해운전자성별      72738 non-null object
가해운전자연령      72727 non-null object
가해운전자상해정도    70172 non-null object
피해운전자차종      72225 non-null object
피해운전자성별      72225 non-null object
피해운전자연령      72049 non-null object
피해운전자상해정도    72225 non-null object
dtypes: int64(4), object(17)
memory usage: 12.5+ MB