#### <span style="color: #00a470"> [Exercise02] 문자열 데이터 처리하기 </span>
- 사고유형, 노면 상태, 도로형태 데이터의 확인 및 처리
    - 대범주-소범주 형태로 되어 있는 문자열을 처리하여 새로운 변수 생성
    - 사고유형_대범주, 노면상태_대범주, 도로형태_대범주
- 데이터 처리 후 사고유형, 노면상태, 도로형태 변수명을 수정
    - 사고유형_소범주
    - 노면상태_소범주
    - 도로형태_소범주
- 피해운전자연령 변수를 수치형으로 수정

In [25]:
import numpy as np
import pandas as pd

In [26]:
df = pd.read_csv('data/01_seoul_accident_raw.csv', encoding='euc-kr')
df.head()

,사고번호,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,법규위반,...,기상상태,도로형태,가해운전자차종,가해운전자성별,가해운전자연령,가해운전자상해정도,피해운전자차종,피해운전자성별,피해운전자연령,피해운전자상해정도
0,A2019010100100001,2019년 1월 1일 00시,서울특별시 강서구 방화동,경상사고,0,0,1,0,차대사람 - 횡단중,보행자보호의무위반,...,맑음,교차로 - 교차로횡단보도내,승용,남,26세,상해없음,보행자,남,40세,경상
1,A2019010100100002,2019년 1월 1일 00시,서울특별시 구로구 고척동,경상사고,0,0,1,0,차대차 - 추돌,안전운전불이행,...,맑음,단일로 - 기타,이륜,남,23세,상해없음,승용,남,71세,경상
2,A2019010100100003,2019년 1월 1일 00시,서울특별시 서초구 서초동,경상사고,0,0,1,0,차대차 - 기타,안전운전불이행,...,맑음,기타 - 기타,승용,남,33세,상해없음,화물,남,51세,경상
3,A2019010100100019,2019년 1월 1일 01시,서울특별시 중구 회현동2가,경상사고,0,0,1,0,차대차 - 측면충돌,안전운전불이행,...,맑음,단일로 - 터널,승용,남,58세,상해없음,승용,남,62세,경상
4,A2019010100100020,2019년 1월 1일 01시,서울특별시 성동구 행당동,경상사고,0,0,1,0,차대사람 - 횡단중,안전운전불이행,...,맑음,교차로 - 교차로부근,승용,남,30세,상해없음,보행자,남,32세,경상

- 사고유형, 노면 상태, 도로형태 데이터의 확인 및 처리
    - 대범주-소범주 형태로 되어 있는 문자열을 처리하여 새로운 변수 생성
    - 사고유형_대범주, 노면상태_대범주, 도로형태_대범주

In [27]:
print(df['사고유형'])
print(df['노면상태'])
print(df['도로형태'])

0        차대사람 - 횡단중
1          차대차 - 추돌
2          차대차 - 기타
3        차대차 - 측면충돌
4        차대사람 - 횡단중
            ...
74480      차대차 - 기타
74481    차대차 - 정면충돌
74482      차대차 - 추돌
74483    차대차 - 측면충돌
74484    차대차 - 측면충돌
Name: 사고유형, Length: 74485, dtype: object
0        포장 - 건조
1        포장 - 건조
2        포장 - 건조
3        포장 - 건조
4        포장 - 건조
          ...
74480    포장 - 건조
74481    포장 - 건조
74482    포장 - 건조
74483    포장 - 건조
74484    포장 - 건조
Name: 노면상태, Length: 74485, dtype: object
0        교차로 - 교차로횡단보도내
1              단일로 - 기타
2               기타 - 기타
3              단일로 - 터널
4           교차로 - 교차로부근
              ...
74480          단일로 - 기타
74481       교차로 - 교차로부근
74482        교차로 - 교차로안
74483          단일로 - 기타
74484          단일로 - 기타
Name: 도로형태, Length: 74485, dtype: object

In [28]:
df['사고유형_대범주'] = df['사고유형'].str.split(' - ').str[0]
df['노면상태_대범주'] = df['노면상태'].str.split(' - ').str[0]
df['도로형태_대범주'] = df['도로형태'].str.split(' - ').str[0]

In [29]:
df.head()

,사고번호,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,법규위반,...,가해운전자성별,가해운전자연령,가해운전자상해정도,피해운전자차종,피해운전자성별,피해운전자연령,피해운전자상해정도,사고유형_대범주,노면상태_대범주,도로형태_대범주
0,A2019010100100001,2019년 1월 1일 00시,서울특별시 강서구 방화동,경상사고,0,0,1,0,차대사람 - 횡단중,보행자보호의무위반,...,남,26세,상해없음,보행자,남,40세,경상,차대사람,포장,교차로
1,A2019010100100002,2019년 1월 1일 00시,서울특별시 구로구 고척동,경상사고,0,0,1,0,차대차 - 추돌,안전운전불이행,...,남,23세,상해없음,승용,남,71세,경상,차대차,포장,단일로
2,A2019010100100003,2019년 1월 1일 00시,서울특별시 서초구 서초동,경상사고,0,0,1,0,차대차 - 기타,안전운전불이행,...,남,33세,상해없음,화물,남,51세,경상,차대차,포장,기타
3,A2019010100100019,2019년 1월 1일 01시,서울특별시 중구 회현동2가,경상사고,0,0,1,0,차대차 - 측면충돌,안전운전불이행,...,남,58세,상해없음,승용,남,62세,경상,차대차,포장,단일로
4,A2019010100100020,2019년 1월 1일 01시,서울특별시 성동구 행당동,경상사고,0,0,1,0,차대사람 - 횡단중,안전운전불이행,...,남,30세,상해없음,보행자,남,32세,경상,차대사람,포장,교차로

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74485 entries, 0 to 74484
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   사고번호       74485 non-null  object
 1   사고일시       74485 non-null  object
 2   시군구        74485 non-null  object
 3   사고내용       74485 non-null  object
 4   사망자수       74485 non-null  int64
 5   중상자수       74485 non-null  int64
 6   경상자수       74485 non-null  int64
 7   부상신고자수     74485 non-null  int64
 8   사고유형       74485 non-null  object
 9   법규위반       74485 non-null  object
 10  노면상태       74485 non-null  object
 11  기상상태       73575 non-null  object
 12  도로형태       74485 non-null  object
 13  가해운전자차종    72734 non-null  object
 14  가해운전자성별    72738 non-null  object
 15  가해운전자연령    72727 non-null  object
 16  가해운전자상해정도  70172 non-null  object
 17  피해운전자차종    72225 non-null  object
 18  피해운전자성별    72225 non-null  object
 19  피해운전자연령    72049 non-null  object
 20  피해운전자상해정도  72225 non-null  object
 21  사고유형_대범주   74485 non-null  object
 22  노면상태_대범주   74485 non-null  object
 23  도로형태_대범주   74485 non-null  object
dtypes: int64(4), object(20)
memory usage: 13.6+ MB

- 데이터 처리 후 사고유형, 노면상태, 도로형태 변수명을 수정
    - 사고유형_소범주
    - 노면상태_소범주
    - 도로형태_소범주

In [31]:
df.rename(columns = {'사고유형':'사고유형_소범주','노면상태':'노면상태_소범주','도로형태':'도로형태_소범주'},inplace=True)
df.head()

,사고번호,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형_소범주,법규위반,...,가해운전자성별,가해운전자연령,가해운전자상해정도,피해운전자차종,피해운전자성별,피해운전자연령,피해운전자상해정도,사고유형_대범주,노면상태_대범주,도로형태_대범주
0,A2019010100100001,2019년 1월 1일 00시,서울특별시 강서구 방화동,경상사고,0,0,1,0,차대사람 - 횡단중,보행자보호의무위반,...,남,26세,상해없음,보행자,남,40세,경상,차대사람,포장,교차로
1,A2019010100100002,2019년 1월 1일 00시,서울특별시 구로구 고척동,경상사고,0,0,1,0,차대차 - 추돌,안전운전불이행,...,남,23세,상해없음,승용,남,71세,경상,차대차,포장,단일로
2,A2019010100100003,2019년 1월 1일 00시,서울특별시 서초구 서초동,경상사고,0,0,1,0,차대차 - 기타,안전운전불이행,...,남,33세,상해없음,화물,남,51세,경상,차대차,포장,기타
3,A2019010100100019,2019년 1월 1일 01시,서울특별시 중구 회현동2가,경상사고,0,0,1,0,차대차 - 측면충돌,안전운전불이행,...,남,58세,상해없음,승용,남,62세,경상,차대차,포장,단일로
4,A2019010100100020,2019년 1월 1일 01시,서울특별시 성동구 행당동,경상사고,0,0,1,0,차대사람 - 횡단중,안전운전불이행,...,남,30세,상해없음,보행자,남,32세,경상,차대사람,포장,교차로

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74485 entries, 0 to 74484
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   사고번호       74485 non-null  object
 1   사고일시       74485 non-null  object
 2   시군구        74485 non-null  object
 3   사고내용       74485 non-null  object
 4   사망자수       74485 non-null  int64
 5   중상자수       74485 non-null  int64
 6   경상자수       74485 non-null  int64
 7   부상신고자수     74485 non-null  int64
 8   사고유형_소범주   74485 non-null  object
 9   법규위반       74485 non-null  object
 10  노면상태_소범주   74485 non-null  object
 11  기상상태       73575 non-null  object
 12  도로형태_소범주   74485 non-null  object
 13  가해운전자차종    72734 non-null  object
 14  가해운전자성별    72738 non-null  object
 15  가해운전자연령    72727 non-null  object
 16  가해운전자상해정도  70172 non-null  object
 17  피해운전자차종    72225 non-null  object
 18  피해운전자성별    72225 non-null  object
 19  피해운전자연령    72049 non-null  object
 20  피해운전자상해정도  72225 non-null  object
 21  사고유형_대범주   74485 non-null  object
 22  노면상태_대범주   74485 non-null  object
 23  도로형태_대범주   74485 non-null  object
dtypes: int64(4), object(20)
memory usage: 13.6+ MB

- 피해운전자연령 변수를 수치형으로 수정

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74485 entries, 0 to 74484
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   사고번호       74485 non-null  object
 1   사고일시       74485 non-null  object
 2   시군구        74485 non-null  object
 3   사고내용       74485 non-null  object
 4   사망자수       74485 non-null  int64
 5   중상자수       74485 non-null  int64
 6   경상자수       74485 non-null  int64
 7   부상신고자수     74485 non-null  int64
 8   사고유형_소범주   74485 non-null  object
 9   법규위반       74485 non-null  object
 10  노면상태_소범주   74485 non-null  object
 11  기상상태       73575 non-null  object
 12  도로형태_소범주   74485 non-null  object
 13  가해운전자차종    72734 non-null  object
 14  가해운전자성별    72738 non-null  object
 15  가해운전자연령    72727 non-null  object
 16  가해운전자상해정도  70172 non-null  object
 17  피해운전자차종    72225 non-null  object
 18  피해운전자성별    72225 non-null  object
 19  피해운전자연령    72049 non-null  object
 20  피해운전자상해정도  72225 non-null  object
 21  사고유형_대범주   74485 non-null  object
 22  노면상태_대범주   74485 non-null  object
 23  도로형태_대범주   74485 non-null  object
dtypes: int64(4), object(20)
memory usage: 13.6+ MB

In [34]:
df['피해운전자연령']

0        40세
1        71세
2        51세
3        62세
4        32세
        ...
74480    41세
74481    21세
74482    29세
74483    22세
74484    22세
Name: 피해운전자연령, Length: 74485, dtype: object

In [35]:
df['피해운전자연령'] = df['피해운전자연령'].str.replace('세','')
df['피해운전자연령'] = df['피해운전자연령'].str.replace(' 이상','')
try:
    df['피해운전자연령'] = df['피해운전자연령'].astype('int')
except:
    df['피해운전자연령'] = df['피해운전자연령'].astype('float')

In [36]:
df['피해운전자연령']

0        40.0
1        71.0
2        51.0
3        62.0
4        32.0
         ...
74480    41.0
74481    21.0
74482    29.0
74483    22.0
74484    22.0
Name: 피해운전자연령, Length: 74485, dtype: float64